### ISSUE TITLE
Tried and working in Test but not working in Production

### ISSUE THREAD

**Issue by gabriellebautista** [tomasbjerre/settings-synchronizer-for-bitbucket-plugin#9]
The only differences I can see is the amount of git repos, We have 13,000 git repos and We are using BB 4.9.0

**Comment by tomasbjerre** [comment]
In what way does it not work? No repos get synced? Some get synced? GUI crashes?

If you look in Developer Tools console log in Chrome, F12. Does it say anything?

**Comment by gabriellebautista** [comment]
No repos are get synced (for all the random checks that I did). GUI is not crashing. I can see in the logs that is doing something (one GET for projects then POST calls for the repos) but nothing is updating.

`10.10.10.10 | https | i*E63L30x390x51785x1 | - | 2016-10-04 06:30:59,959 | "GET /rest/api/1.0/projects/ST_D2SA/repos HTTP/1.1" | "https://mybitbucket.com/plugins/servlet/ssfb/globaladminview" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" | - | - | - | - | - | 1bukqwq |`

`10.10.10.10 | https | o*E63L30x391x51888x2 | scmadm | 2016-10-04 06:31:09,730 | "POST /rest/ssfb/1.0/projects/ST_ACT/repos/agile-coaching-tool/repoadmin HTTP/1.1" | "https://mybitbucket.com/plugins/servlet/ssfb/globaladminview" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" | 200 | 66 | 0 | - | 20 | 1bukqwq |`

Here's the browser console
`DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
     at b.default (https://mycodecloud/s/580ffc6b89564839b1fdf2a085e54bc6-CDN/-21210…ec3ac64fb81/_/download/contextbatch/js/_super/batch.js?locale=en-US:54:209)
eve.js?_statichash=580ffc6…-CDN%2F-2121007725%2F6fa4e2c%2F60%2Fd233379505bd…:5 DEPRECATED - requiring 'eve' has been deprecated since AUI 5.7 and will be removed in AUI 6.0.
globaladminview:138 Mixed Content: The page at 'https://mycodecloud/plugins/servlet/ssfb/globaladminview' was loaded over HTTPS, but requested an insecure image 'http://myplace.com/images/feedback/darkblue_collector_image.png'. This content should also be served over HTTPS.
internal-node-modules-atlassian-aui-src-js-aui-internal-deprecation.js?_statichash=580ffc6b89564839…:1 DEPRECATED JS - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.   
     at Object.q.onReady (https://mycodecloud/s/811ebb62b4edddca5a4153d5a31e7284-CDN/-21210…et.layout.entity,bitbucket.layout.base,-_super/batch.js?locale=en-US:793:5)
internal-node-modules-atlassian-aui-src-js-aui-internal-deprecation.js?_statichash=580ffc6b89564839…:1 DEPRECATED JS - Dropdown constructor has been deprecated and will be removed in a future release. Use Dropdown2 instead.   
     at W (https://mycodecloud/download/contextbatch/js/atl.admin,-_super/ba…on=true&locale=en-US&nps-acknowledged=true&supportedApplication=true:140:4)`

**Comment by tomasbjerre** [comment]
What if you try to sync only one repo, on repo level admin page. Does that work?

**Comment by gabriellebautista** [comment]
Even that is not working :( 

Any hack we can do to copy this config to all the repos?

**Comment by tomasbjerre** [comment]
Not that I know of.

Is there any hint in your server logs? Do you have same user privilegies in production as when you tested in test?

**Comment by gabriellebautista** [comment]
I will try to dig up more info in the logs but AFAIK, it's doing something (see initial logs above) and the updates may not have been pushing through.

I am using a system admin account to configure the changes in test and prod.

**Comment by tomasbjerre** [comment]
And you are sure you have latest version, 1.4, in production?

**Comment by gabriellebautista** [comment]
Yes, we are using 1.4 in prod. I will try uninstall/install the plugin just for luck.

**Comment by gabriellebautista** [comment]
Also quick question, in the global config. What is the different between SAVE and SYNC NOW.

**Comment by tomasbjerre** [comment]
Save just persists the selected options. Sync now performs the actual sync.

Den 4 okt. 2016 14:38 skrev "gabriellebautista" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
Save just persists the selected options. Sync now performs the actual sync.

Den 4 okt. 2016 14:38 skrev "gabriellebautista" <notifications@github.com>:

Also quick question, in the global config. What is the different between
SAVE and SYNC NOW.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tomasbjerre/settings-synchronizer-for-bitbucket-plugin/issues/9#issuecomment-251375892>,
or mute the thread

**Comment by gabriellebautista** [comment]
uninstall/install did not help. 

While watching the database, it seems to have inconsistent values on it. Was this suppose to contain all the git repos that needs to be updated? What should this contain?

`SQL> select key_name from PLUGIN_SETTING where lower(key_name) like '%ssfb%';

KEY_NAME`

snapshot 1 
`{"repoSettings":{"ST_2015INTERN-food_buddy":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_5A84B177-java_class":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABTEST-repo1":{"fromProject
":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-adtm":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-disconnected-portal":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":fal
se,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-ebiz":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-attgfpweb":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"bran
chPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-cacher":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-flatironutmcsvloader":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":fa
lse,"branchingModel":false},"ST_2020INT-gfpcommon":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-gfpcpecorrelator1607":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-g
fpdatacorrelator":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-eds-examples":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-edsgatewayclient":{"fromProject":"ST_GSCM","fromR
epo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-external-github-clones":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-mil-ops":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repository
Hooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-gfpconsolidator":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_AEMINTLPS-aemtest1":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"

Snapshot 2
`{"repoSettings":{"ST_2015INTERN-food_buddy":{"fromProject":"ST_GSCM","fromRepo":"aod","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_5A84B177-java_class":{"fromProject":"ST_GSCM","fromRepo":"aod","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABTEST-repo1":{"fromProject":
"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-adtm":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-disconnected-portal":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false
,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_ABSCI-ebiz":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-attgfpweb":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branch
Permissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-cacher":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-flatironutmcsvloader":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":fals
e,"branchingModel":false},"ST_2020INT-gfpcommon":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-gfpcpecorrelator1607":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-gfp
datacorrelator":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-eds-examples":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-edsgatewayclient":{"fromProject":"ST_GSCM","fromRep
o":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-external-github-clones":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ACSIEDS-mil-ops":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHo
oks":true,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_2020INT-gfpconsolidator":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":false,"repositoryPermissions":false,"branchPermissions":false,"pullRequestSettings":false,"branchingModel":false},"ST_AEMINTLPS-aemtest1":{"fromProject":"ST_GSCM","fromRepo":"cscm","repositoryDetails":false,"repositoryHooks":true,"repositoryPermissions":false,"`

**Comment by tomasbjerre** [comment]
Yes you should see all repos there.

When you press save, and look at network tab of Developer Tools in Chrome, you should see `/rest/api/1.0/projects?limit=999999` that returns all projects. And for every project `/rest/api/1.0/projects/" + projectKey + "/repos?limit=999999` that returns all repos for that project. For every repo, you should see a post to `/rest/ssfb/1.0/projects/" + projectKey + "/repos/" + repoSlug + "/repoadmin"``.

So what do you see? =)

**Comment by gabriellebautista** [comment]
Github won't allow me to upload the har dump of what happened but there are a lot of CANCELED status in there. Do you have a place to upload the har dump so you can take a look?

**Comment by tomasbjerre** [comment]
Ok no I believe you =)

And just to make sure. If you try it on just one repo. You *save* first before you press *sync now*? And still nothing is synced from the selected *from repo*.

**Comment by gabriellebautista** [comment]
Ok. I was doing "save" only earlier. Doing a SAVE then SYNC is working on single ones! What to do next?

**Comment by tomasbjerre** [comment]
Ok great! Then I'm pretty sure how to fix it :)

Den 4 okt. 2016 16:17 skrev "gabriellebautista" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
Try 1.5 now, I just released it.

**Comment by gabriellebautista** [comment]
Tomas, thank you so much for your time on this one. I will have to test this next time as my maintenance window is done (for production).

Got one last request, we just want to sync your other great plugin SBCC to all the other repos (and hopefully not disable any existing hooks that each repository has), Would it be possible for an enhancement request?

**Comment by tomasbjerre** [comment]
Yes that would be possible!

Den 4 okt. 2016 23:40 skrev "gabriellebautista" <notifications@github.com>:

**Comment by gabriellebautista** [comment]
We just tried 1.5 in production but it's still not working :(

**Comment by tomasbjerre** [comment]
And you have nothing interesting in your logs? What is the response of the
http requests shown by developer tools?

Den 10 okt. 2016 20:57 skrev "gabriellebautista" <notifications@github.com>:

**Comment by tomasbjerre** [comment]
I made a new release. Hopefully fixed.
